// src/data/properties.js
// Realistic mock property database for Bashabari

export const PROPERTIES = [
  {
    id: 'prop_001',
    title: 'Bright 3-Bedroom Apartment in Gulshan 2',
    titleBn: 'গুলশান ২-এ সুন্দর ৩ বেডরুমের অ্যাপার্টমেন্ট',
    type: 'apartment',
    area: 'Gulshan 2',
    city: 'Dhaka',
    address: 'Road 48, House 12, Gulshan 2, Dhaka 1212',
    price: 45000,
    negotiable: true,
    bedrooms: 3,
    bathrooms: 3,
    size: 1800,
    floor: '6th',
    facing: 'South',
    parking: true,
    available: true,
    availableFrom: '2024-02-01',
    yearBuilt: 2018,
    verified: true,
    featured: true,
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
      'https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    description: 'A beautifully maintained apartment in the heart of Gulshan 2. This south-facing 3-bedroom unit on the 6th floor offers panoramic views of the residential area, natural ventilation throughout the day, and easy access to major corporate offices and restaurants. The building has 24/7 security, a lift, and rooftop access. Ideal for expats or corporate families.',
    descriptionBn: 'গুলশান ২-এর প্রাণকেন্দ্রে সুন্দরভাবে রক্ষণাবেক্ষণ করা একটি অ্যাপার্টমেন্ট। ৬ষ্ঠ তলায় দক্ষিণমুখী এই ৩ বেডরুমের ফ্ল্যাটটি আবাসিক এলাকার মনোরম দৃশ্য, সারাদিন প্রাকৃতিক বায়ুচলাচল এবং প্রধান অফিস ও রেস্তোরাঁগুলোতে সহজ যোগাযোগ প্রদান করে।',
    amenities: ['Gas', 'Electricity Backup', 'Lift', '24/7 Security', 'Rooftop', 'Parking', 'Broadband Ready', 'CCTV'],
    landlord: {
      name: 'Rafiqul Islam',
      phone: '01712-345678',
      whatsapp: '8801712345678',
      verified: true,
      rating: 4.8,
      totalListings: 3,
      memberSince: '2022',
      responseTime: 'Within 1 hour',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rafiqul',
    },
    views: 1247,
    inquiries: 23,
    lat: 23.7936,
    lng: 90.4142,
  },
  {
    id: 'prop_002',
    title: 'Modern 2-Bedroom Flat in Banani',
    titleBn: 'বনানীতে আধুনিক ২ বেডরুমের ফ্ল্যাট',
    type: 'apartment',
    area: 'Banani',
    city: 'Dhaka',
    address: 'Road 11, House 7, Banani, Dhaka 1213',
    price: 32000,
    negotiable: false,
    bedrooms: 2,
    bathrooms: 2,
    size: 1200,
    floor: '4th',
    facing: 'East',
    parking: false,
    available: true,
    availableFrom: '2024-01-15',
    yearBuilt: 2020,
    verified: true,
    featured: true,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
      'https://images.unsplash.com/photo-1556020685-ae41abfc9365?w=800',
    ],
    description: 'Newly renovated 2-bedroom flat in the vibrant Banani area. The apartment features modern fixtures, a spacious living room, and a well-equipped kitchen. Walking distance to Banani 11 restaurants, cafes, and shopping. Perfect for young professionals or couples looking for a stylish urban home.',
    descriptionBn: 'বনানীর প্রাণবন্ত এলাকায় নতুনভাবে সংস্কারকৃত ২ বেডরুমের ফ্ল্যাট। আধুনিক সুযোগ-সুবিধা, প্রশস্ত লিভিং রুম এবং সুসজ্জিত রান্নাঘর সহ।',
    amenities: ['Gas', 'Electricity Backup', 'Security Guard', 'Broadband Ready', 'Intercom'],
    landlord: {
      name: 'Nasrin Akter',
      phone: '01855-234567',
      whatsapp: '8801855234567',
      verified: true,
      rating: 4.6,
      totalListings: 1,
      memberSince: '2023',
      responseTime: 'Within 2 hours',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nasrin',
    },
    views: 876,
    inquiries: 15,
    lat: 23.7946,
    lng: 90.4058,
  },
  {
    id: 'prop_003',
    title: 'Spacious 4-Bedroom House in Dhanmondi',
    titleBn: 'ধানমন্ডিতে প্রশস্ত ৪ বেডরুমের বাড়ি',
    type: 'house',
    area: 'Dhanmondi',
    city: 'Dhaka',
    address: 'Road 27, House 14, Dhanmondi, Dhaka 1209',
    price: 60000,
    negotiable: true,
    bedrooms: 4,
    bathrooms: 3,
    size: 2400,
    floor: 'Ground + 1st',
    facing: 'North',
    parking: true,
    available: true,
    availableFrom: '2024-03-01',
    yearBuilt: 2015,
    verified: true,
    featured: false,
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
    ],
    description: 'A rare standalone house in the prestigious Dhanmondi area. Spread across two floors with a private garden, this 4-bedroom property is ideal for large families. Close to top schools including Residential Model School and Maple Leaf International, and minutes from Lake Dhanmondi.',
    descriptionBn: 'মর্যাদাপূর্ণ ধানমন্ডি এলাকায় একটি বিরল স্বাধীন বাড়ি। ব্যক্তিগত বাগান সহ দুই তলায় বিস্তৃত এই ৪ বেডরুমের সম্পত্তি বড় পরিবারের জন্য আদর্শ।',
    amenities: ['Gas', 'Electricity Backup', 'Private Garden', 'Parking', 'Security Guard', 'Store Room', 'Servant Quarter', 'Rooftop'],
    landlord: {
      name: 'Md. Kamal Hossain',
      phone: '01911-456789',
      whatsapp: '8801911456789',
      verified: true,
      rating: 4.9,
      totalListings: 2,
      memberSince: '2021',
      responseTime: 'Within 30 mins',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kamal',
    },
    views: 2341,
    inquiries: 41,
    lat: 23.7465,
    lng: 90.3764,
  },
  {
    id: 'prop_004',
    title: 'Cozy 1-Bedroom Sublet in Mirpur 10',
    titleBn: 'মিরপুর ১০-এ আরামদায়ক ১ বেডরুমের সাবলেট',
    type: 'sublet',
    area: 'Mirpur 10',
    city: 'Dhaka',
    address: 'Block C, Road 5, Mirpur 10, Dhaka 1216',
    price: 8500,
    negotiable: true,
    bedrooms: 1,
    bathrooms: 1,
    size: 550,
    floor: '3rd',
    facing: 'West',
    parking: false,
    available: true,
    availableFrom: '2024-01-20',
    yearBuilt: 2012,
    verified: false,
    featured: false,
    images: [
      'https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=800',
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800',
    ],
    description: 'A clean, furnished 1-bedroom sublet in a well-connected part of Mirpur 10. Minutes from Mirpur 10 Metro Station, making your daily commute effortless. Gas and electricity included. Ideal for single working professionals or students.',
    descriptionBn: 'মিরপুর ১০-এর সু-সংযুক্ত এলাকায় একটি পরিষ্কার, আসবাবপত্র সহ ১ বেডরুমের সাবলেট। মেট্রো স্টেশন থেকে মাত্র কয়েক মিনিট।',
    amenities: ['Gas Included', 'Electricity Included', 'Furnished', 'WiFi Ready', 'Metro Nearby'],
    landlord: {
      name: 'Sadia Rahman',
      phone: '01633-567890',
      whatsapp: '8801633567890',
      verified: false,
      rating: 4.2,
      totalListings: 1,
      memberSince: '2023',
      responseTime: 'Within 3 hours',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sadia',
    },
    views: 432,
    inquiries: 8,
    lat: 23.8065,
    lng: 90.3665,
  },
  {
    id: 'prop_005',
    title: 'Premium Duplex in Uttara Sector 7',
    titleBn: 'উত্তরা সেক্টর ৭-এ প্রিমিয়াম ডুপ্লেক্স',
    type: 'apartment',
    area: 'Uttara',
    city: 'Dhaka',
    address: 'Sector 7, Road 3, House 21, Uttara, Dhaka 1230',
    price: 55000,
    negotiable: false,
    bedrooms: 4,
    bathrooms: 4,
    size: 2200,
    floor: '5th & 6th',
    facing: 'South-East',
    parking: true,
    available: true,
    availableFrom: '2024-02-15',
    yearBuilt: 2019,
    verified: true,
    featured: true,
    images: [
      'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?w=800',
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    ],
    description: 'An exceptional duplex apartment in the planned township of Uttara. Spanning two floors with private staircase, 4 spacious bedrooms, a family lounge on the upper floor, and a wide balcony overlooking tree-lined streets. Near Uttara Model Town, Hazrat Shahjalal International Airport, and the upcoming BRT line.',
    descriptionBn: 'উত্তরার পরিকল্পিত শহরতলীতে একটি অসাধারণ ডুপ্লেক্স অ্যাপার্টমেন্ট। ব্যক্তিগত সিঁড়ি সহ দুই তলা বিস্তৃত, ৪টি প্রশস্ত বেডরুম এবং গাছপালাযুক্ত রাস্তার দিকে বড় বারান্দা।',
    amenities: ['Gas', 'Generator', 'Lift', 'Parking', 'CCTV', 'Gym Access', 'Rooftop BBQ', 'Community Hall', '24/7 Security'],
    landlord: {
      name: 'Arif Billah',
      phone: '01777-678901',
      whatsapp: '8801777678901',
      verified: true,
      rating: 5.0,
      totalListings: 4,
      memberSince: '2020',
      responseTime: 'Within 1 hour',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Arif',
    },
    views: 3102,
    inquiries: 57,
    lat: 23.8759,
    lng: 90.3795,
  },
  {
    id: 'prop_006',
    title: 'Affordable 2-Bedroom in Mohammadpur',
    titleBn: 'মোহাম্মদপুরে সাশ্রয়ী ২ বেডরুমের ফ্ল্যাট',
    type: 'apartment',
    area: 'Mohammadpur',
    city: 'Dhaka',
    address: 'Tajmahal Road, Block B, Mohammadpur, Dhaka 1207',
    price: 15000,
    negotiable: true,
    bedrooms: 2,
    bathrooms: 2,
    size: 900,
    floor: '2nd',
    facing: 'North',
    parking: false,
    available: true,
    availableFrom: '2024-01-01',
    yearBuilt: 2010,
    verified: true,
    featured: false,
    images: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
      'https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=800',
    ],
    description: 'Well-maintained 2-bedroom flat in the heart of Mohammadpur. Close to markets, schools, and public transport. Gas line connected, electricity backup available. A great value option for families or two working professionals.',
    descriptionBn: 'মোহাম্মদপুরের প্রাণকেন্দ্রে ভালোভাবে রক্ষণাবেক্ষণ করা ২ বেডরুমের ফ্ল্যাট। বাজার, স্কুল এবং গণপরিবহনের কাছে।',
    amenities: ['Gas', 'Electricity Backup', 'Security Guard', 'Near Market'],
    landlord: {
      name: 'Rina Begum',
      phone: '01555-789012',
      whatsapp: '8801555789012',
      verified: true,
      rating: 4.4,
      totalListings: 2,
      memberSince: '2022',
      responseTime: 'Within 4 hours',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rina',
    },
    views: 654,
    inquiries: 11,
    lat: 23.7584,
    lng: 90.3554,
  },
  {
    id: 'prop_007',
    title: '3-Bedroom Flat in Bashundhara R/A',
    titleBn: 'বসুন্ধরা আবাসিকে ৩ বেডরুমের ফ্ল্যাট',
    type: 'apartment',
    area: 'Bashundhara',
    city: 'Dhaka',
    address: 'Block G, Road 12, Bashundhara R/A, Dhaka 1229',
    price: 28000,
    negotiable: false,
    bedrooms: 3,
    bathrooms: 2,
    size: 1450,
    floor: '7th',
    facing: 'East',
    parking: true,
    available: false,
    availableFrom: '2024-04-01',
    yearBuilt: 2017,
    verified: true,
    featured: false,
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800',
      'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800',
    ],
    description: 'Modern 3-bedroom apartment in the planned Bashundhara Residential Area. Part of a gated compound with generator backup, CCTV, and trained security. Quiet, safe neighborhood — perfect for families with children.',
    descriptionBn: 'পরিকল্পিত বসুন্ধরা আবাসিক এলাকায় আধুনিক ৩ বেডরুমের অ্যাপার্টমেন্ট। জেনারেটর ব্যাকআপ, সিসিটিভি এবং প্রশিক্ষিত নিরাপত্তা সহ গেটেড কমপাউন্ডের অংশ।',
    amenities: ['Gas', 'Generator', 'CCTV', 'Lift', 'Parking', 'Playground', 'Security'],
    landlord: {
      name: 'Tanvir Ahmed',
      phone: '01988-890123',
      whatsapp: '8801988890123',
      verified: true,
      rating: 4.7,
      totalListings: 5,
      memberSince: '2021',
      responseTime: 'Within 2 hours',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tanvir',
    },
    views: 891,
    inquiries: 19,
    lat: 23.8152,
    lng: 90.4264,
  },
  {
    id: 'prop_008',
    title: 'Bachelor-Friendly Sublet in Rayer Bazar',
    titleBn: 'রায়েরবাজারে ব্যাচেলর-বান্ধব সাবলেট',
    type: 'sublet',
    area: 'Rayer Bazar',
    city: 'Dhaka',
    address: 'Rayer Bazar, Dhaka 1209',
    price: 6000,
    negotiable: true,
    bedrooms: 1,
    bathrooms: 1,
    size: 380,
    floor: '1st',
    facing: 'South',
    parking: false,
    available: true,
    availableFrom: '2024-01-10',
    yearBuilt: 2008,
    verified: false,
    featured: false,
    images: [
      'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=800',
    ],
    description: 'Simple, clean sublet for bachelors or students. All bills included. Near BUET and Dhanmondi. Very safe building with iron gate and guard.',
    descriptionBn: 'ব্যাচেলর বা ছাত্রদের জন্য সাধারণ, পরিষ্কার সাবলেট। সব বিল অন্তর্ভুক্ত। বুয়েট এবং ধানমন্ডির কাছে।',
    amenities: ['All Bills Included', 'Security Guard', 'Near University', 'WiFi'],
    landlord: {
      name: 'Fahim Hasan',
      phone: '01644-901234',
      whatsapp: '8801644901234',
      verified: false,
      rating: 4.1,
      totalListings: 1,
      memberSince: '2023',
      responseTime: 'Same day',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fahim',
    },
    views: 234,
    inquiries: 5,
    lat: 23.7350,
    lng: 90.3627,
  },
]

// Helper to get featured
export const getFeatured = () => PROPERTIES.filter(p => p.featured && p.available)

// Helper to get by id
export const getById = (id) => PROPERTIES.find(p => p.id === id)

// Areas list for filter
export const AREAS = [
  'All Areas', 'Gulshan', 'Banani', 'Dhanmondi', 'Uttara',
  'Mirpur', 'Mohammadpur', 'Bashundhara', 'Rayer Bazar', 'Tejgaon',
  'Khilgaon', 'Badda', 'Khilkhet', 'Baridhara', 'Motijheel',
]

// Statistics
export const STATS = {
  listings:  '12,400+',
  cities:    '18',
  landlords: '4,200+',
  renters:   '32,000+',
}

// Testimonials
export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Mehedi Hassan',
    nameBn: 'মেহেদী হাসান',
    role: 'Software Engineer, Dhaka',
    roleBn: 'সফটওয়্যার ইঞ্জিনিয়ার, ঢাকা',
    text: 'After 2 months of searching on Facebook groups and dealing with fake listings, I found my Gulshan apartment on Bashabari in 3 days. The verification system actually works.',
    textBn: 'ফেসবুক গ্রুপে ২ মাস ভুয়া লিস্টিং দেখার পর, মাত্র ৩ দিনে বাশাবাড়িতে গুলশানের ফ্ল্যাট পেয়েছি। যাচাই ব্যবস্থাটা সত্যিই কাজ করে।',
    rating: 5,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mehedi',
    area: 'Gulshan 2',
  },
  {
    id: 2,
    name: 'Farhana Kabir',
    nameBn: 'ফারহানা কবির',
    role: 'University Lecturer, Chittagong',
    roleBn: 'বিশ্ববিদ্যালয় শিক্ষক, চট্টগ্রাম',
    text: 'The WhatsApp direct contact feature saved me so much time. I spoke to the landlord directly, no middleman, no hidden fees. Moved into my new flat within a week.',
    textBn: 'হোয়াটসঅ্যাপ সরাসরি যোগাযোগের ফিচারটি আমার অনেক সময় বাঁচিয়েছে। সরাসরি মালিকের সাথে কথা বললাম, কোনো দালাল নেই, কোনো লুকানো ফি নেই।',
    rating: 5,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Farhana',
    area: 'Agrabad, Chittagong',
  },
  {
    id: 3,
    name: 'Sabbir Chowdhury',
    nameBn: 'সাব্বির চৌধুরী',
    role: 'Business Owner, Sylhet',
    roleBn: 'ব্যবসায়ী, সিলেট',
    text: 'Listed my two properties here and got genuine inquiries within 48 hours. The dashboard makes it easy to manage everything. Far better than posting on random Facebook groups.',
    textBn: 'এখানে আমার দুটো সম্পত্তি লিস্ট করলাম এবং ৪৮ ঘণ্টার মধ্যে প্রকৃত জিজ্ঞাসা পেলাম। ড্যাশবোর্ড সবকিছু সহজে পরিচালনা করতে সাহায্য করে।',
    rating: 5,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sabbir',
    area: 'Sylhet City',
  },
]
